<a href="https://colab.research.google.com/github/julianovale/simulacao_python/blob/master/0003_Kronecker_Simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Produto (01)

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([0,1,0])

In [ ]:
print("Matrizes originais")
print(a)
print(b)

Matrizes originais
[1 2 3]
[0 1 0]


In [ ]:
resultado = np.kron(a, b) ## Produto de Kronecker

In [ ]:
print('Produto de kronecker das matrizes a e b')
print(resultado)

Produto de kronecker das matrizes a e b
[0 1 0 0 2 0 0 3 0]


## Produto (2)

In [ ]:
x = np.arange(9).reshape(3,3)
y = np.arange(3,12).reshape(3,3)

In [ ]:
print("Matrizes originais")
print(x)
print(y)

Matrizes originais
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
resultado = np.kron(x, y) ## Produto de Kronecker

In [ ]:
print('Produto de kronecker das matrizes x e y')
print(resultado)

Produto de kronecker das matrizes x e y
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


## Soma


In [14]:
x = np.arange(4).reshape(2,2)
y = np.arange(3,12).reshape(3,3)

In [15]:
print("Matrizes originais")
print(x)
print(y)

Matrizes originais
[[0 1]
 [2 3]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
ident2 = np.identity(2)
ident3 = np.identity(3)
resultado = np.kron(x,ident3)+np.kron(y,ident2)

In [21]:
print('Soma de kronecker das matrizes x e y')
print(resultado)

Soma de kronecker das matrizes x e y
[[ 3.  0.  4.  1.  5.  0.]
 [ 0.  3.  0.  4.  1.  5.]
 [ 6.  0.  7.  0.  8.  1.]
 [ 2.  6.  0. 10.  0.  8.]
 [ 9.  2. 10.  0. 14.  0.]
 [ 0.  9.  2. 10.  0. 14.]]
